-- Seed all 31 skills into the skills table
-- Run this in Supabase SQL Editor after applying schema.sql

INSERT INTO public.skills (slug, name, description, category, status) VALUES
('content-strategist', 'Content Strategist', 'Analyzes business goals and creates comprehensive content strategies', 'strategy', 'active'),
('on-page-optimizer', 'On-Page Optimizer', 'Optimizes content for keywords, semantic richness, and technical SEO', 'seo', 'active'),
('technical-seo-auditor', 'Technical SEO Auditor', 'Audits websites for crawlability, indexability, and Core Web Vitals', 'seo', 'active'),
('keyword-researcher', 'Keyword Researcher', 'Identifies high-intent keywords and maps them to funnel stages', 'seo', 'active'),
('competitor-intelligence', 'Competitor Intelligence', 'Analyzes competitor strategies, content gaps, and backlink profiles', 'research', 'active'),
('aeo-geo-strategist', 'AEO/GEO Strategist', 'Optimizes content for AI citations and featured snippets', 'seo', 'active'),
('link-building-outreach', 'Link Building & Outreach', 'Crafts personalized outreach campaigns and builds relationships', 'off-page', 'active'),
('pseo-pipeline', 'pSEO Pipeline', 'Designs data-driven programmatic SEO content generation', 'automation', 'active'),
('content-brief-writer', 'Content Brief Writer', 'Creates detailed, actionable briefs for writers', 'content', 'active'),
('copywriter', 'Copywriter', 'Writes compelling headlines, ad copy, and landing pages', 'content', 'active'),
('social-media-manager', 'Social Media Manager', 'Plans content calendars and optimizes for platform algorithms', 'social', 'active'),
('paid-ads-manager', 'Paid Ads Manager', 'Creates and optimizes Google Ads, Meta Ads, and LinkedIn campaigns', 'ads', 'active'),
('analytics-expert', 'Analytics Expert', 'Analyzes data, builds dashboards, and provides actionable insights', 'analytics', 'active'),
('conversion-optimizer', 'Conversion Optimizer', 'Analyzes user behavior and optimizes conversion funnels', 'cro', 'active'),
('brand-voice-writer', 'Brand Voice Writer', 'Defines and maintains consistent brand voice and tone', 'brand', 'active'),
('email-marketing-specialist', 'Email Marketing Specialist', 'Designs sequences and optimizes deliverability', 'email', 'active'),
('local-seo-manager', 'Local SEO Manager', 'Optimizes Google Business Profiles and local citations', 'local', 'active'),
('video-script-writer', 'Video Script Writer', 'Writes scripts and optimizes video content for SEO', 'video', 'active'),
('reputation-manager', 'Reputation Manager', 'Monitors brand sentiment and manages reviews', 'reputation', 'active'),
('market-researcher', 'Market Researcher', 'Analyzes market trends and competitive landscapes', 'research', 'active'),
('forecasting-revenue', 'Revenue Forecaster', 'Builds predictive models and projects revenue growth', 'forecasting', 'active'),
('reporting-automation', 'Reporting Automation', 'Builds automated dashboards and data pipelines', 'automation', 'active'),
('playbook-creator', 'Playbook Creator', 'Documents SOPs and creates playbooks', 'operations', 'active'),
('off-page-optimizer', 'Off-Page Optimizer', 'Builds backlinks and manages brand mentions', 'off-page', 'active'),
('agentic-marketing-os', 'AgenticMarketingPro Atlas', 'Master orchestrator of all AI marketing agents', 'orchestration', 'active'),
('onboarding-agent', 'Onboarding Agent', 'Interactive client onboarding and profile creation', 'operations', 'active'),
('martech-integration-agent', 'Martech Integration', 'Collects and tests API credentials for all tools', 'integration', 'active'),
('seo-data-pipeline', 'SEO Data Pipeline', 'Pulls keyword, backlink, and traffic data from APIs', 'data', 'active'),
('content-production-pipeline', 'Content Production Pipeline', 'Automates blog post creation and publishing', 'automation', 'active'),
('site-monitoring-pipeline', 'Site Monitoring Pipeline', 'Checks uptime, speed, and Core Web Vitals', 'monitoring', 'active'),
('competitor-intelligence-mesh', 'Competitor Intelligence Mesh', 'Tracks competitor rankings, content, and mentions', 'research', 'active');
