import sys
import json
sys.path.insert(0, r"F:\Agentic Marketing Pro\marketing\infrastructure")

from api_client.ga4 import GA4Client

client = GA4Client()
print("Client initialized:", client._client is not None)
print("Property:", client.property_id)

if client._client:
    print()
    print("=== Traffic Overview (last 7 days) ===")
    report = client.traffic_overview(days=7)
    print(f"Total sessions: {report.get('total_sessions')}")
    print(f"Total users: {report.get('total_users')}")
    print(f"New users: {report.get('new_users')}")
    print(f"Conversions: {report.get('conversions')}")
    print()
    print("=== Daily Breakdown ===")
    for day in report.get("daily_breakdown", []):
        print(f"  {day['date']}: {day['sessions']} sessions, {day['users']} users, bounce {day['bounce_rate']}%, avg {day['avg_session_duration']}s")

    print()
    print("=== Channel Performance ===")
    channels = client.channel_performance(days=7)
    for ch in channels[:10]:
        print(f"  {ch.get('sessionDefaultChannelGroup', '?')}: {ch.get('sessions', '0')} sessions, {ch.get('users', '0')} users, {ch.get('conversions', '0')} conv")

    print()
    print("=== Top Landing Pages ===")
    landings = client.landing_pages(days=7, limit=5)
    for lp in landings:
        print(f"  {lp.get('landingPage', '?')[:80]}: {lp.get('sessions', '0')} sessions, {lp.get('users', '0')} users")

    # Write a weekly report to the vault
    print()
    print("=== Writing weekly report to vault ===")
    import os
    from datetime import datetime
    vault = r"F:\Agentic Marketing Pro\marketing\AgenticMarketingPro-Vault\03-SEO-Intelligence"
    os.makedirs(vault, exist_ok=True)
    out_path = os.path.join(vault, "ga4-weekly-log.md")
    today = datetime.now().strftime("%Y-%m-%d")

    md = [
        f"# GA4 Weekly Log — {today}",
        "",
        f"*Property: {client.property_id} | Period: last 7 days*",
        "",
        "## Summary",
        "",
        f"- **Total Sessions:** {report.get('total_sessions', 0)}",
        f"- **Total Users:** {report.get('total_users', 0)}",
        f"- **New Users:** {report.get('new_users', 0)}",
        f"- **Conversions:** {report.get('conversions', 0)}",
        "",
        "## Daily Breakdown",
        "",
        "| Date | Sessions | Users | Bounce% | Avg Time |",
        "|---|---:|---:|---:|---:|",
    ]
    for day in report.get("daily_breakdown", []):
        md.append(f"| {day['date']} | {day['sessions']} | {day['users']} | {day['bounce_rate']}% | {day['avg_session_duration']}s |")

    md += ["", "## Channel Performance", "", "| Channel | Sessions | Users | Conversions |", "|---|---:|---:|---:|"]
    for ch in channels:
        md.append(f"| {ch.get('sessionDefaultChannelGroup', '?')} | {ch.get('sessions', 0)} | {ch.get('users', 0)} | {ch.get('conversions', 0)} |")

    md += ["", "## Top Landing Pages", "", "| Page | Sessions | Users |", "|---|---:|---:|"]
    for lp in landings[:20]:
        md.append(f"| {lp.get('landingPage', '?')[:100]} | {lp.get('sessions', 0)} | {lp.get('users', 0)} |")

    md.append("")
    md.append("---")
    md.append(f"*Generated by ga4-analytics skill at {datetime.now().isoformat()}*")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(md))
    print(f"  Written to: {out_path}")